name: Flake health checker

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "flake.lock"
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at 00:00
  workflow_dispatch: # Allows triggering from the GitHub UI

permissions:
  pull-requests: write # Allows writing comments on PRs

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check flake.lock health
        uses: DeterminateSystems/flake-checker-action@v13

        with:
          flake-lock-path: flake.lock
          fail-mode: true
