name: Release image

on:
  workflow_run:
    workflows: ["Build & cache image"]
    types: [completed]

permissions:
  contents: write

jobs:
  release:
    name: Publish release image
    runs-on: ubuntu-latest

    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'v')

    steps:
      - name: Download CI artifact
        uses: actions/download-artifact@v8
        with:
          name: fydetab-duo-nixos.img.zst
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate checksums
        run: |
          mv img.img.zst fydetab-duo-nixos.img.zst

          # GitHub release assets must be <2GB; split if needed.
          SIZE=$(stat -c %s fydetab-duo-nixos.img.zst)
          if [ "$SIZE" -gt 2147483648 ]; then
            split -b 2000M fydetab-duo-nixos.img.zst fydetab-duo-nixos.img.zst.part-
            rm fydetab-duo-nixos.img.zst
          fi

          sha256sum fydetab-duo-nixos.img.zst* > SHA256SUMS
          cat SHA256SUMS

      - name: Release image
        uses: softprops/action-gh-release@v3

        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          generate_release_notes: true

          files: |
            fydetab-duo-nixos.img.zst*
            SHA256SUMS
